// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RainbowSix.Common.Database.Entities;

#nullable disable

namespace RainbowSix.Common.Database.Migrations
{
    [DbContext(typeof(RainbowSixDbContext))]
    partial class RainbowSixDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaximumQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subtitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.LastSoldAt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MarketDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarketDataId");

                    b.ToTable("LastSoldAt");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.MarketData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("MarketData");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MarketDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ViewerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MarketDataId");

                    b.HasIndex("ViewerId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.PaymentOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid?>("TradeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TransactionFee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TradeId");

                    b.ToTable("PaymentOptions");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientIpCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeCommunicationPreference")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("CodeGenerationPreference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("MaskedPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOnPlatform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlatformType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RememberMeTicket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpaceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwoFactorAuthenticationTicket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Stat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveCount")
                        .HasColumnType("int");

                    b.Property<int>("HighestPrice")
                        .HasColumnType("int");

                    b.Property<int>("LowestPrice")
                        .HasColumnType("int");

                    b.Property<Guid>("MarketDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MarketDataId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TradesLimitationsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ViewerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ViewerId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.TradeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TradeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeItems");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.UserGamePurchaseLimitations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveTransactionCount")
                        .HasColumnType("int");

                    b.Property<int>("ResolvedTransactionCount")
                        .HasColumnType("int");

                    b.Property<int>("ResolvedTransactionPeriodInMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PurchaseLimitations");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.UserGameResaleLock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("SaleLimitationsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SaleLimitationsId");

                    b.ToTable("ResaleLocks");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.UserGameSaleLimitations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveTransactionCount")
                        .HasColumnType("int");

                    b.Property<int>("ResolvedTransactionCount")
                        .HasColumnType("int");

                    b.Property<int>("ResolvedTransactionPeriodInMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SaleLimitations");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.UserGameTradesLimitations", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SellId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuyId");

                    b.HasIndex("SellId");

                    b.ToTable("TradesLimitations");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Viewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ViewerMetaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ViewerMetaId");

                    b.ToTable("Viewer");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.ViewerMeta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActiveTradeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ActiveTradeId");

                    b.ToTable("ViewerMetas");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.LastSoldAt", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.MarketData", "MarketData")
                        .WithMany("LastSoldAt")
                        .HasForeignKey("MarketDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketData");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Node", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RainbowSix.Common.Database.Entities.MarketData", "MarketData")
                        .WithMany()
                        .HasForeignKey("MarketDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RainbowSix.Common.Database.Entities.Viewer", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("MarketData");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.PaymentOption", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RainbowSix.Common.Database.Entities.Trade", null)
                        .WithMany("PaymentOptions")
                        .HasForeignKey("TradeId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Stat", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.MarketData", "MarketData")
                        .WithMany("Stats")
                        .HasForeignKey("MarketDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MarketData");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Tag", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.Item", null)
                        .WithMany("Tags")
                        .HasForeignKey("ItemId");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Trade", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.UserGameTradesLimitations", "Viewer")
                        .WithMany()
                        .HasForeignKey("ViewerId");

                    b.Navigation("Viewer");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.TradeItem", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RainbowSix.Common.Database.Entities.Trade", null)
                        .WithMany("TradeItems")
                        .HasForeignKey("TradeId");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.UserGameResaleLock", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.UserGameSaleLimitations", "SaleLimitations")
                        .WithMany("ResaleLocks")
                        .HasForeignKey("SaleLimitationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaleLimitations");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.UserGameTradesLimitations", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.UserGamePurchaseLimitations", "Buy")
                        .WithMany()
                        .HasForeignKey("BuyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RainbowSix.Common.Database.Entities.UserGameSaleLimitations", "Sell")
                        .WithMany()
                        .HasForeignKey("SellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buy");

                    b.Navigation("Sell");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Viewer", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.ViewerMeta", "Meta")
                        .WithMany()
                        .HasForeignKey("ViewerMetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.ViewerMeta", b =>
                {
                    b.HasOne("RainbowSix.Common.Database.Entities.Trade", "ActiveTrade")
                        .WithMany()
                        .HasForeignKey("ActiveTradeId");

                    b.Navigation("ActiveTrade");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Item", b =>
                {
                    b.Navigation("Tags");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.MarketData", b =>
                {
                    b.Navigation("LastSoldAt");

                    b.Navigation("Stats");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.Trade", b =>
                {
                    b.Navigation("PaymentOptions");

                    b.Navigation("TradeItems");
                });

            modelBuilder.Entity("RainbowSix.Common.Database.Entities.UserGameSaleLimitations", b =>
                {
                    b.Navigation("ResaleLocks");
                });
#pragma warning restore 612, 618
        }
    }
}
